---
- name: Basic Linux Configuration
  hosts: all

  pre_tasks:
    - name: Installing base packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - vim
          - sudo
        state: present

  roles:
    - iptables
    - users
    - docker
    - ssh
